version: '3.4'
services:
  app:
    build:
      context: ./app
    volumes:
      - dist:/opt/app/dist/
      - type: bind
        source: ./app/
        target: /opt/app/
    ports:
      - 1234:1234
  api:
    build:
      context: ./api
    volumes:
      - type: bind
        source: ./api/
        target: /opt/api/
    ports:
      - 3000:3000
  so_jobs_api_stub:
    build:
      context: ./so_jobs_api_stub
    volumes:
      - type: bind
        source: ./so_jobs_api_stub/
        target: /opt/so_jobs_api_stub/
    ports:
      - 4000:4000
volumes:
  dist:
