version: '3.4'
services:
  app:
    build:
      context: ./app
    ports:
      - 1234:1234
  api:
    build:
      context: ./api
    ports:
      - 3000:3000
  so_jobs_api_stub:
    build:
      context: ./so_jobs_api_stub
    ports:
      - 4000:4000
