name: CI

on: [push]

jobs:
  api_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: api
    - run: npm test
      working-directory: api
      env:
        CI: true
  app_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: app
    - run: npm test
      working-directory: app
      env:
        CI: true
  e2e_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
      working-directory: e2e
    - run: npm install
      working-directory: app
    - run: npm run start
      working-directory: app
    - run: ./node_modules/wait-on/bin/wait-on http://127.0.0.1:1234
      working-directory: e2e
    - run: npm test
      working-directory: e2e
      env:
        CI: true
